Team-return/JOBIS-DSM-ANDROID

- presentation/src/main/java/team/retum/jobis_android/feature/auth/signin/SignInScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
> 각종 ui 개선작업을 진행하였습니다.
- 로그인 페이지 포커스 아웃 추가
- 기업 조회 리스트 shadow 추가
- 기업 상세 패이지에서 기업 조회하기 헤더 제거
> 🔗 :: (#48) [BAC-433] UI 오류 개선

- data/src/main/java/team/retum/data/remote/api/UserApi.kt
- data/src/main/java/team/retum/data/remote/request/user/SendVerificationCodeRequest.kt
- domain/src/main/java/team/retum/domain/param/user/SendVerificationCodeParam.kt
- gradle/wrapper/gradle-wrappers.properties
- presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/resetpassword/ResetPasswordViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/signup/SignUpViewModel.kt
> 비밀번호 재설정 기능을 구현했습니다.
- 이메일 인증코드 로직 예외처리
- 변경된 명세 따라 수정 (userName 제거)
- ResetPasswordScreen navigate animation 개선
- ResetPasswordScreen ui 간격 수정
> 🔗 : : (#50) [BAC-428] 로그인 비밀번호 변경 기능 구현

- data/src/main/java/team/retum/data/remote/api/UserApi.kt
- data/src/main/java/team/retum/data/remote/datasource/declaration/UserDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/UserDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/request/user/SendVerificationCodeRequest.kt
- data/src/main/java/team/retum/data/remote/response/user/SignUpResponse.kt
- data/src/main/java/team/retum/data/repository/UserRepositoryImpl.kt
- domain/src/main/java/team/retum/domain/param/user/SendVerificationCodeParam.kt
- presentation/src/main/java/team/retum/jobis_android/contract/SignUpContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/setpassword/SetPasswordScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/studentinfo/StudentInfoScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/verifyemail/VerifyEmailScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/resetpassword/ResetPasswordViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/signup/SignUpViewModel.kt
> 회원가입 버그를 수정했습니다
- 회원가입 버튼 enabled 처리
- 회원가입 버튼 imePadding 처리
> 🔗 :: (#52) [BAC-436] 회원가입 버그 수정

- data/src/main/java/team/retum/data/remote/datasource/declaration/UserDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/UserDataSourceImpl.kt
- data/src/main/java/team/retum/data/repository/UserRepositoryImpl.kt
- data/src/main/java/team/retum/data/storage/UserDataStorage.kt
- data/src/main/java/team/retum/data/storage/UserDataStorageImpl.kt
- domain/src/main/java/team/retum/domain/repository/UserRepository.kt
- domain/src/main/java/team/retum/domain/usecase/user/SignOutUseCase.kt
- presentation/src/main/java/team/retum/jobis_android/contract/HomeContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/home/HomeViewModel.kt
- presentation/src/main/res/values/strings.xml
> 로그아웃 기능을 구현했습니다.
- 로그아웃 모달 구현
- 내부 저장된 유저 정보 초기화 로직 구현
- 회원가입 스크린 뒤로가기 로직 버그 수정
> 🔗 :: (#54) [BAC-438] 로그아웃 구현하기

- data/src/main/java/team/retum/data/remote/api/ReviewApi.kt
- data/src/main/java/team/retum/data/remote/datasource/declaration/ReviewDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/ReviewDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/response/review/FetchReviewDetailsResponse.kt
- data/src/main/java/team/retum/data/remote/response/review/FetchReviewsResponse.kt
- data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/java/team/retum/data/repository/ReviewRepositoryImpl.kt
- domain/src/main/java/team/retum/domain/entity/review/ReviewDetailsEntity.kt
- domain/src/main/java/team/retum/domain/entity/review/ReviewsEntity.kt
- domain/src/main/java/team/retum/domain/repository/ReviewRepository.kt
- domain/src/main/java/team/retum/domain/usecase/review/FetchReviewDetailsUseCase.kt
- presentation/src/main/java/team/retum/jobis_android/contract/ReviewContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/interviewdetails/InterviewDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/interviewdetails/ReviewDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisRoute.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/review/ReviewViewModel.kt
- presentation/src/main/res/drawable/ic_edit.xml
- presentation/src/main/res/values/strings.xml
> 🔗 :: (#59) [BAC-460] 면접 후기 상세 조회 기능 구현

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/team/retum/jobis_android/contract/RecruitmentContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/BookmarkedScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/VibrationManager.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/component/Filter.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomBar.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
> 기업 리스트와 모집의뢰서 리스트 검색 기능을 구현했습니다.
-
> 🔗 :: (#63) [BAC-464] 기업 모집의뢰서 검색 기능 구현

- presentation/src/main/java/team/retum/jobis_android/contract/ApplicationContract.kt
- presentation/src/main/java/team/retum/jobis_android/contract/CompanyContract.kt
- presentation/src/main/java/team/retum/jobis_android/contract/RecruitmentContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/application/ApplicationViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
> 기업, 모집의뢰서 상세보기 기능을 리팩토링 합니다.
- 기업 상세조회 details 분리
- 모집의뢰서 상세조회 details 분리
> 🔗 :: (#65) [BAC-466] 상세보기 리팩토링

- buildSrc/src/main/kotlin/Dependency.kt
- buildSrc/src/main/kotlin/Version.kt
- presentation/src/main/java/team/retum/jobis_android/root/JobisAppState.kt
- presentation/src/main/java/team/retum/jobis_android/root/JobisBasicToast.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/component/JobisSnackBarHost.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/component/ToastLayout.kt
> 토스트 시스템을 적용하였습니다.
- 토스트 시스템 세팅
> 🔗 :: (#67) [BAC-467] 토스트 구현

- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/res/drawable/ic_notification.xml
> 알림 아이콘을 구현했습니다.
- 홈 스크린에 알림 아이콘 추가
> 🔗 :: (#69) [BAC-487] 알림 아이콘 구현

- presentation/src/main/java/team/retum/jobis_android/feature/auth/changepassword/ComparePasswordScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signin/SignInScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/verifyemail/VerifyEmailScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/BookmarkRecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MenuScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/main/MainScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/review/PostReviewScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/review/ReviewDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisRoute.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationProperties.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomNavigationItem.kt
> navigation 로직을 리팩토링 했습니다.
- Screen navController 인자 모두 제거
- navigate 함수 전역 관리 로직 구현
- JobisRoute -> NavigationRoute로 네이밍 변경
> 🔗 :: (#77) [BAC-499] navigation 리팩토링

- data/src/main/java/team/retum/data/remote/api/ApplicationApi.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/ApplicationsDataSourceImpl.kt
- data/src/main/java/team/retum/data/util/HttpHandler.kt
- di/src/main/java/team/retum/di/NetworkModule.kt
- domain/src/main/java/team/retum/domain/entity/applications/AppliedCompanyHistoriesEntity.kt
- domain/src/main/java/team/retum/domain/exception/Exception.kt
- presentation/src/main/java/team/retum/jobis_android/contract/application/ApplicationContract.kt
- presentation/src/main/java/team/retum/jobis_android/contract/file/FileContract.kt
- presentation/src/main/java/team/retum/jobis_android/contract/home/HomeContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
- presentation/src/main/java/team/retum/jobis_android/util/FileUtil.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/application/ApplicationViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/file/FileViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/home/HomeViewModel.kt
- presentation/src/main/res/values/strings.xml
> 지원하기 로직을 리팩토링 했습니다.
- 파일 다중 선택 기능 추가
- 파일 관련 예외 처리 추가
- 모집의뢰서 상세 -> 기업 상세 navigate 안되던 버그 수정
- JobisImage들 Image로 변경
- fileName 함수 내부 구현 변경 -> 파일 이름 안 불러와지던 버그 수정
> 🔗 :: (#86) [BAC-502] 지원하기 파일 로직 리팩토링

- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/main/MainScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/notification/NotificationsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/component/Header.kt
- presentation/src/main/res/values/strings.xml
> 알림 목록 스크린 퍼블리싱 진행
- HomeScreen, MyPageScreen 에서 NotificationsScreen으로 navigate 로직 추가
> 🔗 :: (#91) [BAC-518] 알림 목록 퍼블리싱

- data/src/main/java/team/retum/data/remote/api/CompanyApi.kt
- data/src/main/java/team/retum/data/remote/api/ReviewApi.kt
- data/src/main/java/team/retum/data/remote/datasource/declaration/CompanyDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/declaration/ReviewDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/CompanyDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/ReviewDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/request/review/PostReviewRequest.kt
- data/src/main/java/team/retum/data/remote/response/company/FetchReviewableCompaniesResponse.kt
- data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/java/team/retum/data/repository/CompanyRepositoryImpl.kt
- data/src/main/java/team/retum/data/repository/ReviewRepositoryImpl.kt
- domain/src/main/java/team/retum/domain/entity/company/ReviewableCompaniesEntity.kt
- domain/src/main/java/team/retum/domain/param/review/PostReviewParam.kt
- domain/src/main/java/team/retum/domain/repository/CompanyRepository.kt
- domain/src/main/java/team/retum/domain/repository/ReviewRepository.kt
- domain/src/main/java/team/retum/domain/usecase/company/FetchCompanyDetailsUseCase.kt
- domain/src/main/java/team/retum/domain/usecase/company/FetchReviewableCompaniesUseCase.kt
- domain/src/main/java/team/retum/domain/usecase/review/PostReviewUseCase.kt
- presentation/src/main/java/team/retum/jobis_android/contract/company/CompanyContract.kt
- presentation/src/main/java/team/retum/jobis_android/contract/review/ReviewContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/main/MainScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/review/PostReviewScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/review/ReviewViewModel.kt
- presentation/src/main/res/values/strings.xml
> 면접 후기 작성 기능을 구현했습니다.
- post review 기능 구현
> 🔗 :: (#90) [BAC-516] 면접 후기 작성 기능 서버 연동

- presentation/src/main/java/team/retum/jobis_android/feature/main/MainScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/JobisNavigation.kt
- presentation/src/main/java/team/retum/jobis_android/root/navigation/NavigationRoute.kt
- presentation/src/main/java/team/retum/jobis_android/util/compose/navigation/BottomBar.kt
- presentation/src/main/res/values/themes.xml
> system bar padding을 제거했습니다.
- system bar padding을 제거했습니다.
- navigation 중복 select 버그 및 뒤로가기 이벤트 수정
> 🔗 :: (#94) system UI 개선

- data/src/main/java/team/retum/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/java/team/retum/data/remote/api/UserApi.kt
- data/src/main/java/team/retum/data/remote/datasource/implementation/UserDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/response/user/SignInResponse.kt
- data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/java/team/retum/data/repository/UserRepositoryImpl.kt
- data/src/main/java/team/retum/data/storage/UserDataStorage.kt
- data/src/main/java/team/retum/data/storage/UserDataStorageImpl.kt
- di/src/main/java/team/retum/di/NetworkModule.kt
> 토큰 리프레시 로직을 구현했습니다.
- AuthorizationInterceptor token expires at 캐싱 로직 구현
- AuthorizationInterceptor token reissue api 로직 구현
- SignInResponse parameter 네이밍 수정
> 🔗 :: (#97) [BAC-533] 토큰 리프레시 구현

- data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/mypage/MyPageViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
> 이미지 로직을 수정했습니다.
- 모집의뢰서 페이징 로직 제거
- 기업 페이징 로직 제거
페이징 로직 안정화 전까지 미연의 버그를 방지하기 위해 페이징 로직을 제거했습니다...ㅠ
> 🔗 :: (#99) [BAC-545] 이미지 로직 수정

- buildSrc/src/main/kotlin/Dependency.kt
- buildSrc/src/main/kotlin/Version.kt
- presentation/build.gradle.kts
- presentation/src/main/java/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/changepassword/ComparePasswordScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signin/SignInScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/SignUpScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/setpassword/SetPasswordScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/studentinfo/StudentInfoScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/verifyemail/VerifyEmailScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/BookmarkRecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/home/MyPageScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentFilter.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/review/PostReviewScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/review/ReviewDetailsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/root/MainActivity.kt
> Android에서 flow를 수집하는 권장 방법으로 바꿈
collectAsState -> collectAsStateWithLifeCycle
> 🔗 :: (#102) [BAC-534] collectAsStateWithLifecycle

- presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/bugreport/BugViewModel.kt
> 버그 제보 attachments empty 버그를 수정했습니다.
- fileUrls parameter 위치 변경
> 🔗 :: (#110) 버그 제보 이미지 버그 수정

- data/src/main/java/team/retum/data/remote/api/CompanyApi.kt
- data/src/main/java/team/retum/data/remote/api/RecruitmentApi.kt
- data/src/main/java/team/retum/data/remote/datasource/company/CompanyDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/company/CompanyDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/datasource/recruitment/RecruitmentDataSource.kt
- data/src/main/java/team/retum/data/remote/datasource/recruitment/RecruitmentDataSourceImpl.kt
- data/src/main/java/team/retum/data/remote/response/company/FetchCompanyCountResponse.kt
- data/src/main/java/team/retum/data/remote/response/recruitment/FetchRecruitmentCountResponse.kt
- data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/java/team/retum/data/repository/CompanyRepositoryImpl.kt
- data/src/main/java/team/retum/data/repository/RecruitmentRepositoryImpl.kt
- domain/src/main/java/team/retum/domain/entity/company/CompanyCountEntity.kt
- domain/src/main/java/team/retum/domain/entity/recruitment/RecruitmentCountEntity.kt
- domain/src/main/java/team/retum/domain/repository/CompanyRepository.kt
- domain/src/main/java/team/retum/domain/repository/RecruitmentRepository.kt
- domain/src/main/java/team/retum/domain/usecase/company/FetchCompanyCountUseCase.kt
- domain/src/main/java/team/retum/domain/usecase/recruitment/FetchRecruitmentCountUseCase.kt
- presentation/src/main/java/team/retum/jobis_android/contract/company/CompanyContract.kt
- presentation/src/main/java/team/retum/jobis_android/contract/recruitment/RecruitmentContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/company/CompanyViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
> 리컴포지션이 무한반복되어 메모리 누수가 발생합니다.
- 리컴포지션이 일어나지 않게 하며 페이징 로직을 변경하였습니다.
> 🔗 :: (#117) [BAC-574] infinite recomposition

- presentation/src/main/java/team/retum/jobis_android/contract/code/CodeContract.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentFilter.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/root/RootScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/code/CodeViewModel.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
> recruitment filter 내부 코드를 개선했습니다.
- job, tech code 로직 리팩토링
> 🔗 :: (#121) [BAC-581] recruitment filter 리팩토링

- data/src/main/java/team/retum/data/remote/request/bug/ReportBugRequest.kt
- data/src/main/java/team/retum/data/remote/url/JobisUrl.kt
- domain/src/main/java/team/retum/domain/param/bugreport/ReportBugParam.kt
- presentation/src/main/java/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
- presentation/src/main/java/team/retum/jobis_android/viewmodel/bugreport/BugViewModel.kt
> 버그 제보 시 첨부파일 타입을 옵셔널로 변경하였습니다.
- s3 이미지 url 변경
- attachment url 옵셔널로 변경
- report bug 로직 변경
> 🔗 :: (#123) [BAC-570] 버그 제보 이미지 옵셔널 처리

- presentation/src/main/java/team/retum/jobis_android/feature/main/HomeScreen.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentFilter.kt
- presentation/src/main/java/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
> 필터 job code 버그를 수정했습니다.
- job code optional 처리
- Home Screen notification icon 제거
> 🔗 :: (#125) 필터 코드 버그 수정

- presentation/src/main/java/team/retum/jobis_android/feature/auth/signup/studentinfo/StudentInfoScreen.kt
> 회원가입 학번 입력 버그를 수정했습니다.
- grade, class, number 길이 제한 설정
- grade = 1, class = 1, number = 2
> 🔗 :: (#128) 회원가입 학번 버그 수정

- data/src/main/java/team/retum/data/remote/api/StudentApi.kt
- presentation/src/main/java/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
- presentation/src/main/res/values/strings.xml
> 비밀번호 재설정 kotlin null point exception 버그를 수정했습니다.
- return type 변경
- string resource 오타 수정
> 🔗 :: (#131) 비밀번호 재설정 버그 수정

- data/src/main/kotlin/team/retum/data/remote/api/StudentApi.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/student/StudentDataSource.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/student/StudentDataSourceImpl.kt
- data/src/main/kotlin/team/retum/data/remote/request/student/ChangePasswordRequest.kt
- data/src/main/kotlin/team/retum/data/remote/request/student/ResetPasswordRequest.kt
- data/src/main/kotlin/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/kotlin/team/retum/data/repository/StudentRepositoryImpl.kt
- domain/src/main/kotlin/team/retum/domain/param/students/ChangePasswordParam.kt
- domain/src/main/kotlin/team/retum/domain/param/students/ResetPasswordParam.kt
- domain/src/main/kotlin/team/retum/domain/repository/StudentRepository.kt
- domain/src/main/kotlin/team/retum/domain/usecase/student/ChangePasswordUseCase.kt
- domain/src/main/kotlin/team/retum/domain/usecase/student/ResetPasswordUseCase.kt
- presentation/src/main/kotlin/team/retum/jobis_android/JobisApp.kt
- presentation/src/main/kotlin/team/retum/jobis_android/contract/resetpassword/ResetPasswordContract.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/navigation/AuthNavigation.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/resetpassword/ResetPasswordViewModel.kt
> 비밀번호 재설정 로직을 리팩토링 했습니다.                                                                                                           
- forgotten_password, password 분류
- password navigation animation 수정
> 🔗 :: (#138) 비밀번호 재설정 리팩토링

- data/src/main/kotlin/team/retum/data/interceptor/AuthorizationInterceptor.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordVerifyEmailScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/navigation/AuthNavigation.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/resetpassword/ResetPasswordViewModel.kt
- presentation/src/main/res/values/strings.xml
> RecruitmentsScreen, CompaniesScreen ui를 개선했습니다.
- item shadow 제거
- 상단 padding 제거
- 검색결과 컴포넌트 애니메이션 적용
- 비밀번호 재설정 버그 수정
> 🔗 :: (#137) [BAC-595] list UI 개선

- presentation/src/main/kotlin/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
> 기업 리스트 중첩 버그를 수정했습니다.
- 기업 리스트 중복 선언 제거
> 🔗:: (#142) 기업 리스트 버그 수정

- data/src/main/kotlin/team/retum/data/remote/api/RecruitmentApi.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/recruitment/RecruitmentDataSource.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/recruitment/RecruitmentDataSourceImpl.kt
- data/src/main/kotlin/team/retum/data/repository/RecruitmentRepositoryImpl.kt
- domain/src/main/kotlin/team/retum/domain/param/recruitment/FetchRecruitmentsParam.kt
- domain/src/main/kotlin/team/retum/domain/repository/RecruitmentRepository.kt
- domain/src/main/kotlin/team/retum/domain/usecase/recruitment/FetchRecruitmentCountUseCase.kt
- domain/src/main/kotlin/team/retum/domain/usecase/recruitment/FetchRecruitmentsUseCase.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/recruitment/RecruitmentViewModel.kt
> 모집의뢰서 페이지 조회 명세 변경
- page param 제거
- job code param 추가
- tech code param 추가
> 🔗:: (#145) 모집의뢰서 페이지 조회 명세 변경

- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
- presentation/src/main/res/values/strings.xml
> 모집의뢰서 상세보기 버그를 수정했습니다.
<div>
</div>
- 0, Null, empty인 경우 뷰에서 제거
- 모집분야 텍스트 깨짐 해결
- 스켈레톤 애니메이션 적용
> 🔗 :: (#148) 모집의뢰서 상세보기 버그 수정

- presentation/src/main/kotlin/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
> 파일 선택 창에서 전 화면으로 이동하면 ANR이 발생하는 문제를 해결했습니다.
- onAddFile() uri 옵셔널
> 🔗 :: (#156) 파일 뒤로가기 시 앱 튕김

- presentation/src/main/kotlin/team/retum/jobis_android/feature/company/CompanyDetailsScreen.kt
> null 또는 blank 인 경우 스켈레톤 효과를 제거하였습니다.
- 조건문 처리
> 🔗 :: (#160) 기업 상세 스켈레톤 항목 수정

- presentation/src/main/res/values-night/themes.xml
- presentation/src/main/res/values/themes.xml
> 안드로이드 기본 스플래시 스크린을 제거했습니다.
- default splash screen 제거
> 🔗 :: (#162) 스플래시 스크린 제거

- data/src/main/kotlin/team/retum/data/remote/response/recruitment/FetchRecruitmentDetailsResponse.kt
- domain/src/main/kotlin/team/retum/domain/entity/recruitment/RecruitmentDetailsEntity.kt
- presentation/src/main/kotlin/team/retum/jobis_android/contract/recruitment/RecruitmentContract.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
> 모집의뢰서 상세보기의 정규식 전환시 수당의 타입을 변경했습니다.
- long? -> String?으로 변경
> 🔗 :: (#168) 정규식 전환시 수당 타입 변경

- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentFilter.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
> 기술 코드 필터 UI를 개선하였습니다.
- 필터 버튼 패딩 수정
- 기술 필터 expanded 시 half expanded 상태 skip 되게 설정
> 🔗 :: (#175) 기술 코드 필터 UI 개선

- domain/src/main/kotlin/team/retum/domain/enums/DevelopmentArea.kt
- presentation/src/main/kotlin/team/retum/jobis_android/contract/bugreport/BugReportContract.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/bugreport/BugViewModel.kt
- presentation/src/main/res/values/strings.xml
> 버그 제보에서 발생하는 버그를 수정하였습니다.
- 분야 고정 버그 수정
- 이미지 null 오류 수정
- 버그 이미지 로직 리팩토링
> 🔗 :: (#176) 버그 제보 버그 수정

- data/src/main/kotlin/team/retum/data/remote/request/application/ApplyCompanyRequest.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/application/ApplicationViewModel.kt
> 모집의뢰서 지원 시 url이 첨부되지 않는 버그를 수정했습니다.
- dialog button state 호출 부분 추가
- 파일 선택되지 않은 경우 ?.run{}을 통한 예외 처리
> 🔀 :: (#184) 지원 url 요청 안되는 버그 해결

- data/src/main/kotlin/team/retum/data/remote/api/ApplicationApi.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/application/ApplicationDataSource.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/application/ApplicationDataSourceImpl.kt
- data/src/main/kotlin/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/kotlin/team/retum/data/repository/ApplicationRepositoryImpl.kt
- domain/src/main/kotlin/team/retum/domain/enums/ApplicationStatus.kt
- domain/src/main/kotlin/team/retum/domain/repository/ApplicationsRepository.kt
- domain/src/main/kotlin/team/retum/domain/usecase/applications/ReApplyCompanyUseCase.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/HomeScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/application/ApplicationViewModel.kt
- presentation/src/main/res/values/strings.xml
> 재지원 기능을 구현하였습니다.
- RecruitmentApplicaitonDialog에 boolean 값 추가
- 비즈니스 로직 작성
> 🔗 :: (#183) 재지원 기능 구현

- data/src/main/kotlin/team/retum/data/remote/response/recruitment/FetchRecruitmentsResponse.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/HomeScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentDetailsScreen.kt
- presentation/src/main/res/values/strings.xml
> 모집의뢰서 명세서 수정 사항을 반영했습니다.
- recruitments réponse 수정
- trainpay, pay 단위 수정
> 🔗 :: (#190) 모집의뢰서 목록 명세 수정 사항 반영

- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/HomeScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/viewmodel/BaseViewModel.kt
> 재지원 요청에 파일이 중복으로 포함되는 버그를 수정하였습니다.
- Dialog dismiss시 view model 객체를 초기화 시키기 위해 viewModelStore.clear() 호출
> 🔗 :: (#198) 재지원 파일 중복 버그 수정

- data/src/main/kotlin/team/retum/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/kotlin/team/retum/data/remote/api/FileApi.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/file/FileDataSource.kt
- data/src/main/kotlin/team/retum/data/remote/datasource/file/FileDataSourceImpl.kt
- data/src/main/kotlin/team/retum/data/remote/request/RequestType.kt
- data/src/main/kotlin/team/retum/data/remote/request/files/CreatePresignedUrlRequest.kt
- data/src/main/kotlin/team/retum/data/remote/request/files/CreatePresignedUrlResponse.kt
- data/src/main/kotlin/team/retum/data/remote/url/JobisUrl.kt
- data/src/main/kotlin/team/retum/data/repository/FileRepositoryImpl.kt
- domain/src/main/kotlin/team/retum/domain/entity/files/PresignedUrlEntity.kt
- domain/src/main/kotlin/team/retum/domain/param/files/PresignedUrlParam.kt
- domain/src/main/kotlin/team/retum/domain/repository/FileRepository.kt
- domain/src/main/kotlin/team/retum/domain/usecase/file/CreatePresignedUrlUseCase.kt
- domain/src/main/kotlin/team/retum/domain/usecase/file/UploadPresignedUrlFileUseCase.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/application/ApplicationContract.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/application/ApplicationViewModel.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/application/RecruitmentApplicationDialog.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/bugreport/BugViewModel.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/bugreport/ReportBugScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/common/FileContract.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/common/FileViewModel.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/mypage/MyPageContract.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/mypage/MyPageScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/mypage/MyPageViewModel.kt
- presentation/src/main/res/values/strings.xml
> presigned url을 구현했습니다.
- File 로직 presigned url로 변경
- ReportBug, RecruitmentApplication, EditProfileImage 각 기능에 presigned url 적용
- 그 외 state collect, side effect collect 함수 변경
- 코드 포맷팅 정렬 (ktlint)
- create presigned url 기능 구현 (api ~ view model)
- unused state 및 side effect 제거
없으
> 🔗 :: (#205) presigned url 구현

- data/src/main/kotlin/team/retum/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/kotlin/team/retum/data/remote/api/AuthApi.kt
- data/src/main/kotlin/team/retum/data/remote/request/user/SignInRequest.kt
- data/src/main/kotlin/team/retum/data/remote/request/user/SignUpRequest.kt
- data/src/main/kotlin/team/retum/data/remote/url/JobisUrl.kt
- domain/src/main/kotlin/team/retum/domain/enums/PlatformType.kt
> 로그인, 회원가입, 토큰 재발급 로직에 platform type 파람을 추가하였습니다.
- SignInRequest platform type 추가
- token reissue platform type query string 추가
- SignUpRequest platform type 추가
> 🔗 :: (#210) 로그인 회원가입 토큰 재발급 명세 변경

- presentation/src/main/kotlin/team/retum/jobis_android/MainActivity.kt
> 자동 로그인 로직 버그를 수정하였습니다.
- container.stateFlow.collectAsStateWithLifeCycle() -> mainViewModel.collectAsState()
> 🔗 :: (#204) 자동 로그인 로직 버그 수정

- presentation/src/main/kotlin/team/retum/jobis_android/feature/company/CompaniesScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/company/CompaniesScreenViewModel.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentsScreen.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/recruitment/RecruitmentsScreenViewModel.kt
> 모집의뢰서 검색 및 기업 검색에 디바운스를 적용하였습니다.
- paging 내부 코루틴 로직 Boolean 변수 추가
- name debounce 함수 추가
은오님 Pr 봐주세요
> 🔗 :: (#216) 모집의뢰서 및 기업 검색 디바운스 적용

- data/src/main/kotlin/team/retum/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/kotlin/team/retum/data/remote/api/BookmarkApi.kt
- data/src/main/kotlin/team/retum/data/remote/api/StudentApi.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/auth/resetpassword/ResetPasswordViewModel.kt
- presentation/src/main/kotlin/team/retum/jobis_android/feature/main/mypage/MyPageScreenViewModel.kt
- presentation/src/main/kotlin/team/retum/jobis_android/util/Regex.kt
> api 반환타입에서 Response<Void>를 제거했습니다.
- StudentApi Response<Void> 타입 제거
- BookmarkApi Response<Void> 타입 제거
> 🔗 :: (#218) 반환타입 Response<Void> 제거
